stages:
  - test
  - deploy
  - post_deploy

test:
  image: python:3.8.3
  stage: test
  before_script:
    - cd leidos_project
    - pip install -r requirements.txt

  when: on_success
  tags:
    - docker
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python populate.py
  only:
    - deploy

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - cd leidos_project
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  tags:
    - docker
  environment:
    name: main
    url: $HEROKU_APP_HOST
  only:
    - deploy

post_production:
  stage: post_deploy
  script:
  - heroku run python manage.py migrate -a leidos_app
  - heroku run python populate.py
  only:
  - deploy
