# Generated by Django 4.0 on 2022-02-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('img', models.ImageField(blank=True, upload_to='business_images')),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('slug', models.SlugField(unique=True)),
                ('owner_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('business_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leidos_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images')),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('is_business_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=128)),
                ('price', models.FloatField()),
                ('img', models.ImageField(blank=True, upload_to='item_images')),
                ('section_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leidos_app.menusection')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_from', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('weekday_to', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('from_hour', models.CharField(choices=[('1am', '1am'), ('2am', '2am'), ('3am', '3am'), ('4am', '4am'), ('5am', '5am'), ('6am', '6am'), ('7am', '7am'), ('8am', '8am'), ('9am', '9am'), ('10am', '10am'), ('11am', '11am'), ('12am', '12am'), ('1pm', '1pm'), ('2pm', '2pm'), ('3pm', '3pm'), ('4pm', '4pm'), ('5pm', '5pm'), ('6pm', '6pm'), ('7pm', '7pm'), ('8pm', '8pm'), ('9pm', '9pm'), ('10pm', '10pm'), ('11pm', '11pm'), ('12pm', '12pm')], max_length=5)),
                ('to_hour', models.CharField(choices=[('1am', '1am'), ('2am', '2am'), ('3am', '3am'), ('4am', '4am'), ('5am', '5am'), ('6am', '6am'), ('7am', '7am'), ('8am', '8am'), ('9am', '9am'), ('10am', '10am'), ('11am', '11am'), ('12am', '12am'), ('1pm', '1pm'), ('2pm', '2pm'), ('3pm', '3pm'), ('4pm', '4pm'), ('5pm', '5pm'), ('6pm', '6pm'), ('7pm', '7pm'), ('8pm', '8pm'), ('9pm', '9pm'), ('10pm', '10pm'), ('11pm', '11pm'), ('12pm', '12pm')], max_length=5)),
                ('business_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leidos_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leidos_app.business')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('business_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leidos_app.business')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
